// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AckMessage(arg1) {
  return window['go']['main']['App']['AckMessage'](arg1);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteConsumer(arg1) {
  return window['go']['main']['App']['DeleteConsumer'](arg1);
}

export function DeleteStream(arg1) {
  return window['go']['main']['App']['DeleteStream'](arg1);
}

export function Disconnect(arg1) {
  return window['go']['main']['App']['Disconnect'](arg1);
}

export function DownloadUpdatePackage() {
  return window['go']['main']['App']['DownloadUpdatePackage']();
}

export function ExportConnections(arg1) {
  return window['go']['main']['App']['ExportConnections'](arg1);
}

export function ExportConnectionsToFile(arg1) {
  return window['go']['main']['App']['ExportConnectionsToFile'](arg1);
}

export function FetchConsumerMessages(arg1) {
  return window['go']['main']['App']['FetchConsumerMessages'](arg1);
}

export function GetAppSettings() {
  return window['go']['main']['App']['GetAppSettings']();
}

export function GetLogRetentionSettings() {
  return window['go']['main']['App']['GetLogRetentionSettings']();
}

export function GetSnapshot() {
  return window['go']['main']['App']['GetSnapshot']();
}

export function GetUpdateState() {
  return window['go']['main']['App']['GetUpdateState']();
}

export function GetWindowState() {
  return window['go']['main']['App']['GetWindowState']();
}

export function ImportConnections(arg1) {
  return window['go']['main']['App']['ImportConnections'](arg1);
}

export function ImportConnectionsFromFile(arg1) {
  return window['go']['main']['App']['ImportConnectionsFromFile'](arg1);
}

export function ImportCredentialsFile() {
  return window['go']['main']['App']['ImportCredentialsFile']();
}

export function ImportTLSCAFile() {
  return window['go']['main']['App']['ImportTLSCAFile']();
}

export function ImportTLSCertFile() {
  return window['go']['main']['App']['ImportTLSCertFile']();
}

export function ImportTLSKeyFile() {
  return window['go']['main']['App']['ImportTLSKeyFile']();
}

export function ListConsumers(arg1, arg2) {
  return window['go']['main']['App']['ListConsumers'](arg1, arg2);
}

export function ListCredentialsFiles() {
  return window['go']['main']['App']['ListCredentialsFiles']();
}

export function ListStreams(arg1) {
  return window['go']['main']['App']['ListStreams'](arg1);
}

export function ListTLSCAFiles() {
  return window['go']['main']['App']['ListTLSCAFiles']();
}

export function ListTLSCertFiles() {
  return window['go']['main']['App']['ListTLSCertFiles']();
}

export function ListTLSKeyFiles() {
  return window['go']['main']['App']['ListTLSKeyFiles']();
}

export function NakMessage(arg1) {
  return window['go']['main']['App']['NakMessage'](arg1);
}

export function OpenDownloadedUpdate(arg1) {
  return window['go']['main']['App']['OpenDownloadedUpdate'](arg1);
}

export function Publish(arg1) {
  return window['go']['main']['App']['Publish'](arg1);
}

export function Reply(arg1) {
  return window['go']['main']['App']['Reply'](arg1);
}

export function RepublishMessage(arg1) {
  return window['go']['main']['App']['RepublishMessage'](arg1);
}

export function Request(arg1) {
  return window['go']['main']['App']['Request'](arg1);
}

export function RevealDownloadedUpdate(arg1) {
  return window['go']['main']['App']['RevealDownloadedUpdate'](arg1);
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['App']['SaveAppSettings'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveLogRetentionSettings(arg1) {
  return window['go']['main']['App']['SaveLogRetentionSettings'](arg1);
}

export function SetSubscriptionState(arg1) {
  return window['go']['main']['App']['SetSubscriptionState'](arg1);
}

export function StartManualUpgrade() {
  return window['go']['main']['App']['StartManualUpgrade']();
}

export function Subscribe(arg1) {
  return window['go']['main']['App']['Subscribe'](arg1);
}

export function TermMessage(arg1) {
  return window['go']['main']['App']['TermMessage'](arg1);
}

export function Unsubscribe(arg1) {
  return window['go']['main']['App']['Unsubscribe'](arg1);
}

export function UpdateSubscription(arg1) {
  return window['go']['main']['App']['UpdateSubscription'](arg1);
}

export function UpsertConsumer(arg1) {
  return window['go']['main']['App']['UpsertConsumer'](arg1);
}

export function UpsertStream(arg1) {
  return window['go']['main']['App']['UpsertStream'](arg1);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
