// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';
import {main} from '../models';

export function AckMessage(arg1:domain.MessageActionRequest):Promise<void>;

export function CheckForUpdates():Promise<domain.UpdateInfo>;

export function Connect(arg1:string):Promise<domain.ConnectionProfile>;

export function DeleteConnection(arg1:string):Promise<void>;

export function DeleteConsumer(arg1:domain.ConsumerDeleteRequest):Promise<void>;

export function DeleteStream(arg1:domain.StreamDeleteRequest):Promise<void>;

export function Disconnect(arg1:string):Promise<void>;

export function DownloadUpdatePackage():Promise<domain.UpdateDownloadResult>;

export function ExportConnections(arg1:domain.ExportConnectionsRequest):Promise<domain.ExportConnectionsResponse>;

export function ExportConnectionsToFile(arg1:domain.ExportConnectionsRequest):Promise<domain.ExportConnectionsFileResponse>;

export function FetchConsumerMessages(arg1:domain.ConsumerFetchRequest):Promise<domain.ConsumerFetchResponse>;

export function GetAppSettings():Promise<domain.AppSettings>;

export function GetLogRetentionSettings():Promise<domain.LogRetentionSettings>;

export function GetSnapshot():Promise<domain.Snapshot>;

export function GetUpdateState():Promise<domain.UpdateState>;

export function GetWindowState():Promise<main.WindowState>;

export function ImportConnections(arg1:domain.ImportConnectionsRequest):Promise<domain.ImportConnectionsResponse>;

export function ImportConnectionsFromFile(arg1:domain.ImportConnectionsFromFileRequest):Promise<domain.ImportConnectionsResponse>;

export function ImportCredentialsFile():Promise<domain.ManagedResourceFile>;

export function ImportTLSCAFile():Promise<domain.ManagedResourceFile>;

export function ImportTLSCertFile():Promise<domain.ManagedResourceFile>;

export function ImportTLSKeyFile():Promise<domain.ManagedResourceFile>;

export function ListConsumers(arg1:string,arg2:string):Promise<Array<domain.ConsumerInfo>>;

export function ListCredentialsFiles():Promise<Array<domain.ManagedResourceFile>>;

export function ListStreams(arg1:string):Promise<Array<domain.StreamInfo>>;

export function ListTLSCAFiles():Promise<Array<domain.ManagedResourceFile>>;

export function ListTLSCertFiles():Promise<Array<domain.ManagedResourceFile>>;

export function ListTLSKeyFiles():Promise<Array<domain.ManagedResourceFile>>;

export function NakMessage(arg1:domain.MessageActionRequest):Promise<void>;

export function OpenDownloadedUpdate(arg1:string):Promise<void>;

export function Publish(arg1:domain.PublishRequest):Promise<void>;

export function Reply(arg1:domain.ReplyRequest):Promise<void>;

export function RepublishMessage(arg1:domain.RepublishMessageRequest):Promise<domain.RepublishMessageResponse>;

export function Request(arg1:domain.RequestMessageRequest):Promise<domain.RequestMessageResponse>;

export function RevealDownloadedUpdate(arg1:string):Promise<void>;

export function SaveAppSettings(arg1:domain.AppSettings):Promise<domain.AppSettings>;

export function SaveConnection(arg1:domain.ConnectionInput):Promise<domain.ConnectionProfile>;

export function SaveLogRetentionSettings(arg1:domain.LogRetentionSettings):Promise<domain.LogRetentionSettings>;

export function SetSubscriptionState(arg1:domain.SetSubscriptionStateRequest):Promise<domain.SubscriptionInfo>;

export function StartManualUpgrade():Promise<domain.UpdateInfo>;

export function Subscribe(arg1:domain.SubscribeRequest):Promise<domain.SubscriptionInfo>;

export function TermMessage(arg1:domain.MessageActionRequest):Promise<void>;

export function Unsubscribe(arg1:string):Promise<void>;

export function UpdateSubscription(arg1:domain.UpdateSubscriptionRequest):Promise<domain.SubscriptionInfo>;

export function UpsertConsumer(arg1:domain.ConsumerUpsertRequest):Promise<domain.ConsumerInfo>;

export function UpsertStream(arg1:domain.StreamUpsertRequest):Promise<domain.StreamInfo>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<main.WindowState>;
